### ISSUE TITLE
Call a smart contract

### ISSUE THREAD

**Issue by michielpost** [Koniverse/SubConnect#1]
Hi! I'm exploring the Polkadot/Substrate ecosystem and want to create a dApp that calls a SmartContract.
I found this library to easily connect with one of the browser extensions, but now I want to call a smart contract after the user has connected. 
Is that possible? Can it be implemented once and work with all browser extensions?
Do you have any tips for me on where to start?

**Comment by saltict** [comment]
Sorry @michielpost about late reply!

You also can use signer with [smart contract](https://polkadot.js.org/docs/api-contract/start/contract.read/) call. Here is example code:

```typescript
const contract = await new ContractPromise(api, abi, address);
const address = '...' // Account address
const wallet = getWalletBySource('subwallet-js') as BaseDotsamaWallet;
if (wallet) {
  await wallet.enable()
  const signer = wallet.signer;
  if (signer && signer.signRaw && signer.signPayload) {
    await contract.tx
      .doSomething({ /* Smart contract method input go here */ })
      .signAndSend(
        address,
        { signer },
        async ({ status, dispatchError }) => {
          // Handle status callback here
        }
      );
    //Run something after fisish
  }
}
```
---

**Comment by michielpost** [comment]
Thanks.
I was able to modify the `Sign Dummy` sample and then use the `contract.tx...` with the injected signer. That worked.

What would really help me (as a non react dev) is to have a vanilla-js sample. To really show what this project can do. Now it's very much intertwined with React. So using this without React is a bit complex.

**Comment by saltict** [comment]
I plan to separate `wallet connect` into a npm module that can use from any js code run on browser.

If also can read main concept of connect to Dotsama wallet in this [article](https://github.com/Koniverse/SubConnect/wiki/How-to-integrate-SubWallet-and-other-Dotsama-Wallet-to-DApp) to do it yourseft. It will help interact with extension and other object like signer to use in yout code.
