### ISSUE TITLE
Wagmi connector types are not compatible with latest version of wagmi

### ISSUE THREAD

**Issue by Yuripetusko** [Koniverse/SubConnect#17]
**Describe the bug**
When using SubWalletConnector, the `chains` object from wagmi and rainbowkit is incompatible

**To Reproduce**

```
import { Chain, Wallet } from '@rainbow-me/rainbowkit';

export interface MyWalletOptions {
  chains: Chain[];
}

 const connector = new SubWalletConnector({
      chains,
    });
    
    //Types of property 'public' are incompatible.
    //Type 'RpcUrls' is not assignable to type 'string
```

**Expected behavior**
To have no typescript errors

**Screenshots**
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/666169/226211540-53c68734-0611-4145-b295-fde92943292c.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I had to fork talisman connector to apply the fix also
https://github.com/Yuripetusko/talisman-connectors

**Comment by saltict** [comment]
Fix and deploy: https://www.npmjs.com/package/@subwallet/wagmi-connector/v/0.1.1
