### ISSUE TITLE
have a similar solution like siwe?

### ISSUE THREAD

**Issue by kulame** [Koniverse/SubConnect#7]
**Is your feature request related to a problem? Please describe.**

siwe is Sign-In with Ethereum library
i also need a signin solution with my dapp with substrate.

does subconnect support this feature?  so i can check user id on offchain service at my private server.

**Comment by saltict** [comment]
Hi @kulame, sorry about late reply!

SubConnect is not support exactly what you want. 

But if you need it right now you can do something like https://polkadot.polkassembly.io/ have done. They random some bytes, request signature of it from wallet with signRaw methods. This signature can be use like one time password for address on wallet.
